### PR TITLE
Add an Objective-C implementation

### PR DESCRIPTION
**Pull request by woxtu**
Hi,

This PR adds an Objective-C implementation.

### CODE REVIEW

**Comment by 4kimov** [comment]
Hi @woxtu, thank you very much for the PR! Sent you a maintainer invite to the repo (feel free to push as needed). Looks pretty solid to me, I'll update the website 👍 Is there anything major left to do?

**Comment by woxtu** [comment]
We haven't set up GitHub Actions yet.

**Comment by 4kimov** [comment]
Sounds good 👍  I can see you have access now, so let me know if you have any questions or any issues come up.

Site [updated](https://sqids.org/objective-c). Glad to have Objective-C onboard, thanks for the work! :)

**Comment by woxtu** [comment]
OK, I'll do that and release the first version (just create a tag) later.

**Pull request merged**
